services:
    mssql:
        image: 'mcr.microsoft.com/mssql/server:2019-latest'
        ports:
            - '1433:1433'
        environment:
            - ACCEPT_EULA=Y
            - MSSQL_PID=Express
            - MSSQL_SA_PASSWORD=sqlServer(!)Password
        volumes:
            - './drive:/var/opt/mssql'
        restart: always